spring.application.name=mentorconnect-api


spring.datasource.url=jdbc:postgresql://dpg-d8l6ehe47okc73bg576g-a.oregon-postgres.render.com:5432/auth_db_gk9r
spring.datasource.username=custom
spring.datasource.password=F12suhmsNiiZSMXOdEjqQS2y2WzOoIe9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-super-secret-key-your-super-secret-key
jwt.expiration=86400000